In [89]:
from itertools import cycle
from collections import Counter
import numpy as np

In [122]:
fruits = ["orange","apple","banana","strawberry","kiwi"]
desks = ["A","B","C"]

In [112]:
every_third_char = "".join(fruits)[2::3]


In [113]:
every_third_char

'aepbasaeyw'

In [114]:
x = ""
for i in range(len(fruits)): 
    x +=  "".join(fruits[i][0])
    
x

'oabsk'

In [115]:
res = sorted(fruits, key = lambda x: x.split()[0][2])
y = ""
for i in range(len(res)): 
    y +=  "".join(res[i][0])
    
y

'obask'

In [116]:
res = sorted(fruits , key = lambda x : x.split()[0][-1], reverse= True)
y = ""
for i in range(len(res)): 
    y +=  "".join(res[i][0])
    
y



'skoab'

In [123]:
nl = []
for i , fruit in enumerate(fruits):
    if i%len(desks) ==0:
        nl.append(f'{desks[0]}_{fruit}')
        
    elif i%len(desks) ==1:
        nl.append(f'{desks[1]}_{fruit}')
    elif i%len(desks) ==2:
        nl.append(f'{desks[2]}_{fruit}')

        
print(nl)

['A_orange', 'B_apple', 'C_banana', 'A_strawberry', 'B_kiwi']


In [25]:
ll = [[0,1,2], [3,4,5], [6,7,8]]
ll[0][0::2]

[0, 2]

In [26]:
ll[1:][1][0::2]

[6, 8]

In [29]:
a = np.array(ll)

In [30]:
a[1:, 1]

array([4, 7])

In [33]:
a[:,2]

array([2, 5, 8])

In [35]:
a[1:,:2]

array([[3, 4],
       [6, 7]])

In [39]:
np.arange(25).reshape((5,5))  

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
np.linspace(20,100,30)# here 30 means 30 elements

array([ 20.        ,  22.75862069,  25.51724138,  28.27586207,
        31.03448276,  33.79310345,  36.55172414,  39.31034483,
        42.06896552,  44.82758621,  47.5862069 ,  50.34482759,
        53.10344828,  55.86206897,  58.62068966,  61.37931034,
        64.13793103,  66.89655172,  69.65517241,  72.4137931 ,
        75.17241379,  77.93103448,  80.68965517,  83.44827586,
        86.20689655,  88.96551724,  91.72413793,  94.48275862,
        97.24137931, 100.        ])

In [41]:
np.arange(0,100,30) # here 30 means step is 30 

array([ 0, 30, 60, 90])

In [42]:
np.logspace(1,100,4)# gives 4 log elements betwenn 1 and 100

array([1.e+001, 1.e+034, 1.e+067, 1.e+100])

In [126]:
import csv

a = np.arange(9).reshape((3,3))

with open('/Users/varungandhi/Downloads/myfile.csv', 'w', newline='') as file:
    mywriter = csv.writer(file, delimiter=',')
    mywriter.writerows(a)
    
    
    


In [137]:
with open('/Users/varungandhi/Downloads/example.csv', 'w') as fp:
    
    for i,row in enumerate(a):
        print(i,row)
        for j,val in enumerate(row):
            print(j,val)
            if j!= 2:
                fp.write(str(val) + ",")
            else:
                fp.write(str(val) + "\n")

0 [0 1 2]
0 0
1 1
2 2
1 [3 4 5]
0 3
1 4
2 5
2 [6 7 8]
0 6
1 7
2 8
