In [1]:
import numpy as np

In [2]:
dx = 10.

dy = [10,20,30,40,50,60,70,800,900,1000]

np.gradient(dy, dx, )

array([ 1. ,  1. ,  1. ,  1. ,  1. ,  1. , 37. , 41.5, 10. , 10. ])

In [3]:
f = np.array([1, 2, 4, 7, 11, 16], dtype=float)

np.gradient(f)



array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])

In [4]:
np.gradient(f, 2)


array([0.5 , 0.75, 1.25, 1.75, 2.25, 2.5 ])

In [5]:
x = np.arange(f.size)

np.gradient(f, x)

array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])

In [6]:
x

array([0, 1, 2, 3, 4, 5])