In [120]:

import pandas as pd
import numpy as np

def read_data(path):
    
    df = pd.read_excel(path, sheet_name='Pecs')
    return df

df = read_data('/Volumes/Seagate Backup Plus Drive/historical/1900 - 1919/1916.xlsx')

In [121]:
df1 = df.iloc[3:34, 2:5]
df2 = df.iloc[3:31, 9:12]
df3 = df.iloc[3:34,15:18]
df4 = df.iloc[48:78,2:5]
df5 = df.iloc[48:79, 9:12]
df6 = df.iloc[48:78,15:18]
df7 = df.iloc[93:124,2:5]
df8 = df.iloc[93:124,9:12]
df9 = df.iloc[93:123,15:18]
df10 = df.iloc[138:169,2:5]
df11 = df.iloc[138:168,9:12]
df12 = df.iloc[138:169,15:18]
#df7

In [122]:
def cal(df_1,df_2,df_3, df_4, df_5, df_6, df_7, df_8, df_9, df_10,df_11, df_12):
    
    array_1 = df_1.to_numpy(dtype = int)
    array_2 = df_2.to_numpy(dtype= int)
    array_3 = df_3.to_numpy(dtype= int)
    array_4 = df_4.to_numpy(dtype= int)
    array_5 = df_5.to_numpy(dtype= int)
    array_6 = df_6.to_numpy(dtype= int)
    array_7 = df_7.to_numpy(dtype= int)
    array_8 = df_8.to_numpy(dtype= int)
    array_9 = df_9.to_numpy(dtype= int)
    array_10 = df_10.to_numpy(dtype= int)
    array_11 = df_11.to_numpy(dtype= int)
    array_12= df_12.to_numpy(dtype= int)
    
    #final_array = np.concatenate((array_1, array_2), axis = 0)
    
    final_array = np.concatenate((array_1, array_2, array_3,array_4, array_5,array_6,array_7, array_8, array_9, array_10, array_11, array_12), axis = 0)
    return final_array

In [6]:
year_1890 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1890

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
year_1891 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1891

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 1, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
year_1892 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1892

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [18]:
year_1893 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1893

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
year_1894 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1894

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
year_1895 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1895

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
year_1896 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1896

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
year_1897 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1897

array([[0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       ...,
       [1, 1, 1],
       [1, 1, 1],
       [1, 0, 0]])

In [38]:
year_1898 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1898

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
year_1899 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1899

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [46]:
year_1900 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1900

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [50]:
year_1901 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1901

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
year_1902 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1902

array([[0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
year_1903 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1903

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [71]:
year_1904 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1904

array([[0, 0, 0],
       [1, 1, 1],
       [1, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [75]:
year_1905 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1905

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [1, 1, 1],
       [1, 0, 0],
       [0, 0, 0]])

In [79]:
year_1906 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1906

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [84]:
year_1907 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1907

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [1, 1, 1],
       [0, 0, 0]])

In [88]:
year_1908 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1908

array([[1, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [92]:
year_1909 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1909

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [96]:
year_1910 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1910

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [103]:
year_1911 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1911

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [107]:
year_1912 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1912

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       ...,
       [0, 0, 0],
       [0, 1, 0],
       [1, 0, 0]])

In [111]:
year_1913 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1913

array([[0, 1, 1],
       [1, 1, 0],
       [0, 1, 1],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [115]:
year_1914 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1914

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [119]:
year_1915 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1915

array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [123]:
year_1916 = cal(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
year_1916

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [124]:
def cals(arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8, arr9, arr10, arr11, arr12, arr13, arr14, arr15, arr16,
         arr17,arr18,arr19,arr20,arr21,arr22,arr23,arr24,arr25,arr26,arr27):
    
    years_array = np.concatenate((arr1, arr2, arr3, arr4, arr5, arr6, arr7,
                                  arr8, arr9, arr10, arr11, arr12, arr13, 
                                  arr14, arr15, arr16,arr17,arr18,arr19,
                                  arr20,arr21,arr22,arr23,arr24,arr25,
                                  arr26,arr27), axis = 0)
    final_array = years_array.reshape(years_array.shape[0]*years_array.shape[1])
    
    a_str = ''.join(str(x) for x in final_array)
    
    c_str = a_str.split('0')
    
    a1 = 0
    a2 = 0
    a3 = 0
    a4 = 0
    a5 = 0
    a6 = 0
    a7 = 0
    a8 = 0
    a9 = 0
    a10 = 0
    a11 = 0
    a12 = 0
    a13 = 0
    a14 = 0
    a15 = 0
    a16 = 0
    a17 = 0
    a18 = 0
    a19 = 0
    a20 = 0
    
    find_pattern = ['1', '11', '111', '1111','11111', '111111', '1111111', '11111111',
                   '111111111', '1111111111', '11111111111', '111111111111', '1111111111111',
                   '11111111111111','111111111111111', '1111111111111111', '11111111111111111',
                   '111111111111111111', '1111111111111111111', '11111111111111111111']

    for p in range(len(c_str)):
        if find_pattern[0] == c_str[p]:
            a1+=1
            
        if find_pattern[1] == c_str[p]:
            a2+=1
            
        if find_pattern[2] == c_str[p]:
            a3+=1
            
        if find_pattern[3] == c_str[p]:
            a4+=1
            
        if find_pattern[4] == c_str[p]:
            a5+=1
            
        if find_pattern[5] == c_str[p]:
            a6+=1
            
        if find_pattern[6] == c_str[p]:
            a7+=1
            
        if find_pattern[7] == c_str[p]:
            a8+=1
            
        if find_pattern[8] == c_str[p]:
            a9+=1
            
        if find_pattern[9] == c_str[p]:
            a10+=1
            
        if find_pattern[10] == c_str[p]:
            a11+=1
            
        if find_pattern[11] == c_str[p]:
            a12+=1
            
        if find_pattern[12] == c_str[p]:
            a13+=1
            
        if find_pattern[13] == c_str[p]:
            a14+=1
            
        if find_pattern[14] == c_str[p]:
            a15+=1
        
        if find_pattern[15] == c_str[p]:
            a16+=1
        
        if find_pattern[16] == c_str[p]:
            a17+=1
            
        if find_pattern[17] == c_str[p]:
            a18+=1
            
        if find_pattern[18] == c_str[p]:
            a19+=1
            
        if find_pattern[10] == c_str[p]:
            a20+=1
        
    return a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20

In [125]:
result = cals(year_1890, year_1891, year_1892, year_1893,year_1894, year_1895, 
              year_1896, year_1897, year_1898,year_1899,year_1900, year_1901, 
              year_1902, year_1903, year_1904, year_1905, year_1906, year_1907,
              year_1908, year_1909, year_1910, year_1911, 
              year_1912, year_1913, year_1914, 
              year_1915, year_1916)
result

(502, 70, 50, 31, 13, 10, 8, 2, 4, 5, 3, 0, 1, 1, 2, 0, 0, 1, 0, 3)